version: '3'

services:
  
  pontedera-server:
    build: .
    container_name: pontedera
    volumes:
      - ./src/:/usr/src/app/src/:ro
      - ./tmp:/usr/src/app/tmp:rw
    ports:
      - "5000:5000"
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - PYTHONPATH="$PYTHONPATH":/usr/src/app/src

  redis:
    image: redis:latest
    container_name: pontedera-redis
